name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'drtao-vue-app/**' # 只有子项目代码变化时才触发
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: 'drtao-vue-app/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd drtao-vue-app
        npm ci
        
    - name: Build
      run: |
        cd drtao-vue-app
        npm run build
        
    - name: Copy build files to root
      run: |
        # 清理根目录的旧文件（保留docs文件夹）
        rm -f ./index.html ./favicon.ico ./manifest.webmanifest
        rm -rf ./assets ./js ./css ./sw.js ./workbox-*.js ./registerSW.js
        rm -f ./pwa-*.png ./ui1.jpg
        
        # 复制构建产物到根目录
        cp -r ./drtao-vue-app/dist/* ./
        
        # 创建.nojekyll文件以禁用Jekyll
        touch .nojekyll
        
    - name: Deploy to GitHub Pages
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Auto deploy PWA from drtao-vue-app/dist to root"
        file_pattern: |
          index.html
          favicon.ico
          manifest.webmanifest
          assets/
          pwa-*.png
          ui1.jpg
          sw.js
          workbox-*.js
          registerSW.js
          .nojekyll
